import type {Table,Profile,Field,CardSpec,Result,Point,Source,Filter} from './types';
import {fieldValue,monetary} from './profile';import {sourceAt} from './prepare';
export type RecordRow={index:number;values:Record<string,string|number|null>};
const uniqueSources=(a:Source[])=>[...new Map(a.map(s=>[s.file+'!'+s.sheet+'!'+s.cell,s])).values()].slice(0,100);
export function preparedRows(t:Table,p:Profile){const seen=new Set<string>();return t.rows.flatMap((r,index)=>{if(p.excludeTotals&&r.some(v=>typeof v==='string'&&/^(grand total|sub[ -]?total|sous[ -]?total|total general|total)$/i.test(v.trim())))return [];const key=JSON.stringify(r);if(p.deduplicate&&seen.has(key))return [];seen.add(key);return [{index,values:Object.fromEntries(p.fields.map((f,c)=>[f.id,fieldValue(r[c],f)]))}]})}
function applyFilters(rows:RecordRow[],filters:Filter[],p:Profile){return rows.filter(r=>filters.every(filter=>{const field=p.fields.find(f=>f.id===filter.field);if(!field)return false;const value=r.values[filter.field];if(value==null)return false;const compare=(v:unknown)=>field.kind==='number'?Number(v):String(v).trim().toLowerCase();if(filter.op==='in')return Array.isArray(filter.value)&&filter.value.some(v=>compare(v)===compare(value));if(Array.isArray(filter.value))return false;const right=compare(filter.value),left=compare(value);return filter.op==='eq'?left===right:filter.op==='gte'?left>=right:left<=right}))}
function total(rows:RecordRow[],field:Field,p:Profile){const valid=rows.filter(r=>typeof r.values[field.id]==='number');if(!valid.length)return null;if(field.aggregation==='mean')return valid.reduce((n,r)=>n+Number(r.values[field.id]),0)/valid.length;if(field.aggregation==='count')return valid.length;if(field.aggregation==='last'){const dates=valid.flatMap(r=>typeof r.values[p.dateField]==='string'?[String(r.values[p.dateField])]:[]).sort();if(!dates.length)return null;return valid.filter(r=>r.values[p.dateField]===dates.at(-1)).reduce((n,r)=>n+Number(r.values[field.id]),0)}return valid.reduce((n,r)=>n+Number(r.values[field.id]),0)}
export function periodKey(date:string,period:CardSpec['period']='month'){return period==='year'?date.slice(0,4):period==='quarter'?date.slice(0,4)+'-Q'+Math.ceil(Number(date.slice(5,7))/3):date.slice(0,7)}
function periodSequence(first:string,last:string,period:CardSpec['period']='month'){const start=new Date(first.slice(0,4)+'-'+(period==='quarter'?String((Number(first.at(-1))-1)*3+1).padStart(2,'0'):period==='year'?'01':first.slice(5,7))+'-01T00:00:00Z');const keys:string[]=[];for(let i=0;i<600;i++){const key=periodKey(start.toISOString(),period);if(key>last)break;keys.push(key);start.setUTCMonth(start.getUTCMonth()+(period==='year'?12:period==='quarter'?3:1))}return keys}
function grouped(rows:RecordRow[],field:Field,dimension:string,p:Profile,period?:CardSpec['period']):Point[]{const groups=new Map<string,RecordRow[]>();for(const r of rows){const v=r.values[dimension];if(v==null)continue;const key=period?periodKey(String(v),period):String(v);groups.set(key,[...(groups.get(key)||[]),r])}return [...groups].map(([name,group])=>({name,key:name,value:total(group,field,p),count:group.filter(r=>r.values[field.id]!==null).length})).sort((a,b)=>period?a.name.localeCompare(b.name):(b.value||0)-(a.value||0))}
function quantile(a:number[],p:number){if(!a.length)return null;const pos=(a.length-1)*p,lo=Math.floor(pos),hi=Math.ceil(pos);return a[lo]+(a[hi]-a[lo])*(pos-lo)}
function mean(a:number[]){return a.reduce((n,v)=>n+v,0)/a.length}
function predict(values:number[],method:'naive'|'drift'|'linear',h:number){if(method==='naive')return values.at(-1)!;if(method==='drift')return values.at(-1)!+(values.at(-1)!-values[0])/(values.length-1)*h;const n=values.length,xbar=(n-1)/2,ybar=mean(values),den=values.reduce((sum,_,i)=>sum+(i-xbar)**2,0),slope=values.reduce((sum,y,i)=>sum+(i-xbar)*(y-ybar),0)/den;return ybar+slope*(n-1+h-xbar)}
export function forecastSeries(points:Point[],horizon=6){if(points.length<12||points.some(p=>p.value==null))throw new Error('Forecasting needs at least 12 consecutive observed monthly values. Missing months are not filled with zero.');const y=points.map(p=>p.value!),holdout=Math.min(6,Math.floor(y.length/4)),methods=['naive','drift','linear'] as const;const evaluated=methods.map(method=>{const errors:number[]=[];for(let i=y.length-holdout;i<y.length;i++)errors.push(y[i]-predict(y.slice(0,i),method,1));return {method,errors,mae:mean(errors.map(Math.abs))}}).sort((a,b)=>a.mae-b.mae);const best=evaluated[0],width=quantile(best.errors.map(Math.abs).sort((a,b)=>a-b),.9)||0;const date=new Date(points.at(-1)!.name+'-01T00:00:00Z');const future:Point[]=[];for(let h=1;h<=horizon;h++){date.setUTCMonth(date.getUTCMonth()+1);const value=predict(y,best.method,h);future.push({name:date.toISOString().slice(0,7),value:null,second:value,lower:value-width*Math.sqrt(h),upper:value+width*Math.sqrt(h)})}return {points:[...points,...future],method:best.method,mae:best.mae,holdout};}
export function executeCard(t:Table,p:Profile,s:CardSpec):Result{
 const f=p.fields.find(f=>f.id===s.measure),second=p.fields.find(f=>f.id===s.secondMeasure),dimension=p.fields.find(f=>f.id===s.dimension),date=p.fields.find(f=>f.id===p.dateField);
 const result:Result={id:s.id,tool:s.tool,title:f?.name||'Analysis',status:'ready',unit:f?.unit||'unspecified',value:null,points:[],facts:[],notes:[],sources:[],rowsUsed:0,rowsExcluded:0};
 const block=(why:string)=>({...result,status:'blocked' as const,notes:[why]});
 if(!p.confirmed)return block('Confirm the dataset definitions before calculating.');if(!f||f.kind!=='number'||f.role==='ignore'||f.role==='id')return block('Choose a numeric business measure for this analysis.');
 if(f.aggregation==='none')return block('Choose an explicit aggregation for this numeric measure.');
 const needsDate=['trend','forecast'].includes(s.tool)||f.aggregation==='last';const usedFields=[f,second,dimension,...s.filters.map(filter=>p.fields.find(v=>v.id===filter.field)),...(needsDate?[date]:[])].filter((f):f is Field=>!!f);
 if(usedFields.some(f=>p.issues.some(i=>i.field===f.id&&i.severity==='review')))return block('Resolve the highlighted date, number or unit definition for this measure first.');
 if(s.filters.some(filter=>!p.fields.some(f=>f.id===filter.field)))return block('A filter refers to a field outside this dataset.');
 let rows=applyFilters(preparedRows(t,p),s.filters,p);const eligible=rows.length;
 const scenario=p.fields.find(f=>/^(scenario|basis|data type|type de donnees)$/i.test(f.name));if(scenario){const values=[...new Set(rows.map(r=>String(r.values[scenario.id]??'').toLowerCase()).filter(Boolean))];if(values.length>1)return block('Separate the scenario values with a filter before totaling or comparing this measure. Budget and actual observations are not added together.');if(s.tool==='forecast'&&values.some(v=>/budget|plan|forecast|projection|prevision/.test(v)))return block('Budget or projected scenarios cannot be treated as observed history.')}
 if(f.aggregation==='last'&&s.tool==='trend'){const keys=p.entityKeys.filter(k=>k!==p.dateField);const grouped=new Map<string,Set<string>>();for(const row of rows){const d=String(row.values[p.dateField]??'');const key=JSON.stringify(keys.map(k=>row.values[k]));const seen=grouped.get(d)||new Set<string>();if(seen.has(key))return block('Snapshot history contains repeated entity keys at one date. Confirm product/location keys or duplicate handling.');seen.add(key);grouped.set(d,seen)}}
 if(needsDate&&(!date||date.kind!=='date'))return block('Choose a valid date field for time-based analysis.');
 if(f.aggregation==='last'&&!['trend','forecast'].includes(s.tool)){const latest=rows.flatMap(r=>typeof r.values[p.dateField]==='string'?[String(r.values[p.dateField])]:[]).sort().at(-1);rows=rows.filter(r=>r.values[p.dateField]===latest);result.notes.push('Latest observed snapshot: '+(latest||'unavailable')+'. Historical snapshots are not added together.');
  const keys=p.entityKeys.filter(k=>k!==p.dateField);if(keys.length){const ids=rows.map(r=>JSON.stringify(keys.map(k=>r.values[k])));if(new Set(ids).size!==ids.length)return block('The latest snapshot contains repeated entity keys. Review the product/location keys or duplicate rows before totaling balances.');}else if(rows.length>1)return block('Select entity keys for this multi-row snapshot so overlapping balances are not summed.');
 }
 const paired=['comparison','correlation','ratio'].includes(s.tool);if(paired&&(!second||second.kind!=='number'))return block('Choose a second numeric measure.');
 if(paired)rows=rows.filter(r=>typeof r.values[f.id]==='number'&&typeof r.values[second!.id]==='number');else rows=rows.filter(r=>typeof r.values[f.id]==='number');
 if(needsDate)rows=rows.filter(r=>typeof r.values[p.dateField]==='string');
 const codes=p.currencyField&&usedFields.some(f=>monetary.has(f.role)||/^[A-Z]{3}$/.test(f.unit))?[...new Set(rows.map(r=>String(r.values[p.currencyField]??'UNSPECIFIED').toUpperCase()))]:[];
 if(codes.length>1)return block('These observations contain multiple currencies. Add a currency filter; no combined monetary total is produced.');if(codes.length===1){if(!/^[A-Z]{3}$/.test(codes[0]))return block('Some observations have missing or invalid currency codes.');if(usedFields.some(f=>/^[A-Z]{3}$/.test(f.unit)&&f.unit!==codes[0]))return block('The filtered currency conflicts with the measure’s confirmed currency.');result.unit=codes[0]}
 if(!rows.length)return block('No valid observations match this analysis and its filters.');result.rowsUsed=rows.length;result.rowsExcluded=t.rows.length-rows.length;if(eligible>rows.length)result.notes.push(`${eligible-rows.length} matching rows lack an input required for this calculation.`);
 result.sources=uniqueSources(rows.flatMap(r=>usedFields.map(f=>sourceAt(t,r.index,Number(f.id.slice(1))))));
 const numbers=rows.map(r=>Number(r.values[f.id])),unit=result.unit;result.value=total(rows,f,p);const label=f.aggregation==='last'?'Latest':f.aggregation==='mean'?'Mean':f.aggregation==='count'?'Count':'Total';
 if(s.tool==='summary'){result.title=label+' '+f.name;const sorted=[...numbers].sort((a,b)=>a-b);result.facts=[{label:'Observations',value:numbers.length,unit:'rows'},{label:'Median',value:quantile(sorted,.5)!,unit},{label:'Minimum',value:sorted[0],unit},{label:'Maximum',value:sorted.at(-1)!,unit}];}
 if(s.tool==='trend'||s.tool==='forecast'){
  result.title=f.name+' by '+(s.period||'month');const period=s.tool==='forecast'?'month':s.period||'month',observed=grouped(rows,f,p.dateField,p,period),map=new Map(observed.map(p=>[p.name,p]));const keys=periodSequence(observed[0].name,observed.at(-1)!.name,period);if(keys.length>=600)return block('Choose a shorter date range for this time series.');result.points=keys.map(name=>map.get(name)||{name,value:null,count:0});result.notes.push('Totals cover observed records. The first and last periods may be partial.');
  if(result.points.some(p=>p.value===null))result.notes.push('Unobserved periods appear as gaps, not zero.');
  if(s.tool==='forecast'){if(p.basis!=='observed')return block('Only confirmed observed history can be used for a historical forecast.');if(f.aggregation==='last')return block('Snapshot forecasting needs a dedicated state model; this tool forecasts observed flow measures.');if(f.aggregation!=='sum'&&f.aggregation!=='mean')return block('Choose a supported flow measure.');try{const prediction=forecastSeries(result.points,s.horizon||6);result.points=prediction.points;result.title=f.name+' forecast';result.facts=[{label:'Backtest MAE',value:prediction.mae,unit},{label:'Holdout observations',value:prediction.holdout,unit:'months'}];result.notes.push(`Selected ${prediction.method} against naïve, drift and linear baselines using rolling one-step holdouts. Shaded limits are illustrative ranges from observed backtest errors, not calibrated confidence intervals. Seasonality and external shocks are not modeled.`)}catch(e){return block(e instanceof Error?e.message:'Forecast unavailable.')}}
  else {const ready=result.points.filter(p=>p.value!=null);if(ready.length>=2){const a=ready.at(-2)!,b=ready.at(-1)!;if(result.points.indexOf(b)-result.points.indexOf(a)===1&&a.value!==0)result.facts.push({label:'Change in last observed period',value:(b.value!-a.value!)/Math.abs(a.value!),unit:'percent'})}}
 }
 if(s.tool==='breakdown'){if(!dimension||dimension.kind!=='text'||dimension.role==='ignore')return block('Choose a categorical field for this breakdown.');result.title=f.name+' by '+dimension.name;result.points=grouped(rows,f,dimension.id,p);if(result.points.length>100)return block('This dimension has more than 100 groups. Filter it or choose a more concise dimension.');if(result.points.some(p=>p.value!<0))result.notes.push('Negative values are retained. Category shares are not calculated for signed totals.');}
 if(s.tool==='distribution'){const sorted=[...numbers].sort((a,b)=>a-b),lo=sorted[0],hi=sorted.at(-1)!;result.title=f.name+' distribution';if(!Number.isFinite(hi-lo))return block('The numeric extent exceeds the supported range.');const bins=Math.min(16,Math.max(1,Math.ceil(Math.sqrt(sorted.length)))),width=(hi-lo||1)/bins;result.points=Array.from({length:bins},(_,i)=>({name:(lo+i*width).toLocaleString('en-US',{maximumFractionDigits:2})+'–'+(lo+(i+1)*width).toLocaleString('en-US',{maximumFractionDigits:2}),value:0}));for(const n of sorted)result.points[Math.min(bins-1,Math.floor((n-lo)/width))].value!++;const q1=quantile(sorted,.25)!,q3=quantile(sorted,.75)!,iqr=q3-q1;result.facts=[{label:'Median',value:quantile(sorted,.5)!,unit},{label:'Outside 1.5× IQR',value:sorted.filter(v=>v<q1-1.5*iqr||v>q3+1.5*iqr).length,unit:'rows'}];result.notes.push('Possible outliers are flagged for investigation and remain included.');}
 if(s.tool==='correlation'){if(rows.length<3)return block('At least three complete numeric pairs are required.');const x=numbers,y=rows.map(r=>Number(r.values[second!.id])),mx=mean(x),my=mean(y),xx=x.reduce((n,v)=>n+(v-mx)**2,0),yy=y.reduce((n,v)=>n+(v-my)**2,0);if(!xx||!yy)return block('Correlation is undefined when either measure is constant.');const xy=x.reduce((n,v,i)=>n+(v-mx)*(y[i]-my),0);result.value=xy/Math.sqrt(xx*yy);result.unit='correlation';result.title=f.name+' × '+second!.name;result.points=rows.slice(0,500).map((r,i)=>({name:'Observation '+(r.index+1),value:x[i],second:y[i]}));result.facts=[{label:'Pearson r',value:result.value,unit:'correlation'},{label:'Complete pairs',value:rows.length,unit:'rows'}];result.notes.push('Correlation describes association and does not establish causation. The chart displays the first 500 complete pairs; the statistic uses all complete pairs.');}
 if(s.tool==='comparison'){
  if(f.unit!==second!.unit&&!(codes.length===1&&[f,second!].every(f=>f.unit==='unspecified'||f.unit===codes[0])))return block('A comparison requires matching units and currencies.');if(f.aggregation!==second!.aggregation)return block('A comparison requires the same aggregation basis.');const a=total(rows,f,p),b=total(rows,second!,p);result.title=f.name+' vs '+second!.name;result.value=a!==null&&b!==null?a-b:null;result.points=[{name:f.name,value:a},{name:second!.name,value:b}];result.facts=[{label:'Difference · first minus second',value:result.value!,unit}];if(b!==0&&b!==null)result.facts.push({label:'Difference / second measure',value:result.value!/Math.abs(b),unit:'percent'});if(f.role==='revenue'&&second!.role==='cost'&&a)result.facts.push({label:'Revenue less stated cost / revenue',value:result.value!/a,unit:'percent'});result.notes.push('Both totals use the same complete observations. A revenue/cost difference is not labeled net profit unless the accounting scope establishes it.');
 }
 if(s.tool==='ratio'){if(f.aggregation!=='sum'||second!.aggregation!=='sum')return block('Weighted ratios require two additive flow measures; averages and snapshots need a specific definition.');const a=total(rows,f,p),b=total(rows,second!,p);if(b===null||b<=0)return block('The matching denominator must be positive.');result.title=f.name+' / '+second!.name;result.value=a!/b;result.unit=unit===second!.unit?'ratio':unit+' / '+second!.unit;result.facts=[{label:'Numerator',value:a!,unit},{label:'Denominator',value:b,unit:second!.unit}];result.notes.push('Computed as the sum of matching numerators divided by the sum of matching denominators. Monthly or row ratios are not averaged.');}
 if(result.value!==null&&!Number.isFinite(result.value))return block('The result exceeds the supported numeric range.');if(result.sources.length===100)result.notes.push('Source preview shows up to 100 distinct input cells; the saved table retains all source positions.');return result;
}
