import type {Table,Profile,CardSpec,Plan,AIProposal,AIRequest,Result,Field,Filter} from './types';import {normalize} from './prepare';import {executeCard} from './engine';import {monetary,numericRoles} from './profile';import {AIProposalSchema} from './schema';
export const cardId=()=>crypto.randomUUID();
const definition=(tool:CardSpec['tool'],measure:string,extras:Partial<CardSpec>={}):CardSpec=>({id:cardId(),tool,measure,filters:[],...extras});
export function defaultPlan(t:Table,p:Profile):Plan{const money=p.fields.filter(f=>['revenue','cost','profit','budget','actual'].includes(f.role)),quantities=p.fields.filter(f=>['quantity','stock','duration','rating'].includes(f.role)),fallback=p.fields.filter(f=>f.kind==='number'&&!['id','ignore','unit_price','unit_cost','reorder'].includes(f.role)),measures=[...new Map([...money,...quantities,...fallback].map(f=>[f.id,f])).values()].slice(0,5),dimension=p.fields.find(f=>['region','product','category'].includes(f.role)&&f.unique<=30),cards:CardSpec[]=[];
 const scenario=p.fields.find(f=>/^(scenario|basis|data type|type de donnees)$/i.test(f.name)),scenarioValues=scenario?[...new Set(t.rows.map(r=>String(r[Number(scenario.id.slice(1))]??'').trim()).filter(Boolean))]:[],scenarioFilters=scenario&&scenarioValues.length>1?scenarioValues.slice(0,3).map(value=>[{field:scenario.id,op:'eq' as const,value}]):[[]];
 const currencyIndex=p.fields.findIndex(f=>f.id===p.currencyField),currencies=currencyIndex>=0?[...new Set(t.rows.map(r=>String(r[currencyIndex]??'').trim().toUpperCase()).filter(c=>/^[A-Z]{3}$/.test(c)))]:[];
 for(const f of measures.slice(0,4)){const variants=monetary.has(f.role)&&currencies.length>1?currencies.slice(0,3).map(c=>[{field:p.currencyField,op:'eq' as const,value:c}]):[[]];for(const base of variants)for(const scoped of scenarioFilters)cards.push(definition('summary',f.id,{filters:[...base,...scoped]}))}
 const main=measures[0];if(main){const filters=[...(monetary.has(main.role)&&currencies.length>1?[{field:p.currencyField,op:'eq' as const,value:currencies[0]}]:[]),...scenarioFilters[0]];if(p.dateField)cards.push(definition('trend',main.id,{period:'month',filters}));if(dimension)cards.push(definition('breakdown',main.id,{dimension:dimension.id,filters}));cards.push(definition('distribution',main.id,{filters}));const budget=p.fields.find(f=>f.role==='budget'),actual=p.fields.find(f=>f.role==='actual'),revenue=p.fields.find(f=>f.role==='revenue'),cost=p.fields.find(f=>f.role==='cost'),quantity=p.fields.find(f=>f.role==='quantity');if(budget&&actual&&budget.unit===actual.unit)cards.push(definition('comparison',actual.id,{secondMeasure:budget.id,filters}));else if(revenue&&cost&&revenue.unit===cost.unit)cards.push(definition('comparison',revenue.id,{secondMeasure:cost.id,filters}));if(cost&&quantity)cards.push(definition('ratio',cost.id,{secondMeasure:quantity.id,filters}));}
 return {version:1,cards:cards.slice(0,12),planner:'rules',explanation:`Selected analyses for the confirmed ${p.domain} dataset. Calculations use the declared units and aggregation rules.`,questions:[]};}
export function profileRequest(t:Table,p:Profile,mode:AIRequest['mode'],question='',currentCards:CardSpec[]=[]):AIRequest{return {mode,question,profile:{domain:p.domain,grain:p.grain,basis:p.basis,confirmed:p.confirmed,rows:t.rows.length,fields:p.fields.map(({id,name,kind,role,unit,aggregation,missing,invalid,unique,min,max})=>({id,name,kind,role,unit,aggregation,missing,invalid,unique,min,max}))},currentCards}}
export function validateProposal(input:unknown,request:AIRequest):AIProposal{const proposal=AIProposalSchema.parse(input),ids=new Set(request.profile.fields.map(f=>f.id));if(proposal.fields.some(f=>!ids.has(f.id))||new Set(proposal.fields.map(f=>f.id)).size!==proposal.fields.length)throw new Error('The AI proposed an unknown or duplicate field.');for(const f of proposal.fields){const original=request.profile.fields.find(v=>v.id===f.id)!;if(numericRoles.has(f.role)&&original.kind!=='number'||f.role==='date'&&original.kind!=='date')throw new Error('The AI definition conflicts with the observed field type.');if(request.mode==='plan'&&(f.role!==original.role||f.unit!==original.unit||f.aggregation!==original.aggregation))throw new Error('Confirmed field definitions cannot be changed by a chart request.');if(original.unit!=='unspecified'&&f.unit!==original.unit)throw new Error('The AI proposal conflicts with a known source unit.');}for(const c of proposal.cards){if(!ids.has(c.measure)||c.secondMeasure&&!ids.has(c.secondMeasure)||c.dimension&&!ids.has(c.dimension)||c.filters.some(f=>!ids.has(f.field)))throw new Error('The AI proposed an analysis outside the available fields.');if(request.profile.fields.find(f=>f.id===c.measure)?.kind!=='number')throw new Error('The AI selected a nonnumeric measure.');}return proposal;}
export function applyProposal(proposal:AIProposal,previous:Plan):Plan{if(proposal.action==='clarify')return {...previous,planner:'model',explanation:proposal.explanation,questions:proposal.questions};const cards=proposal.cards.map(c=>({...c,id:cardId()}));const all=proposal.action==='replace'?cards:[...previous.cards,...cards],seen=new Set<string>();return {version:1,cards:all.filter(c=>{const signature=JSON.stringify({...c,id:''});if(seen.has(signature))return false;seen.add(signature);return true}).slice(0,20),planner:'model',explanation:proposal.explanation,questions:proposal.questions};}
function findField(p:Profile,prompt:string,roles:string[]=[]){const normalized=normalize(prompt);return p.fields.filter(f=>f.role!=='ignore'&&f.role!=='id').sort((a,b)=>b.name.length-a.name.length).find(f=>normalized.includes(normalize(f.name)))||p.fields.find(f=>roles.includes(f.role))}
export function interpretQuestion(t:Table,p:Profile,previous:Plan,question:string):Plan{
 const prompt=normalize(question),numeric=p.fields.filter(f=>f.kind==='number'&&!['id','ignore'].includes(f.role));const requestedRoles=prompt.includes('revenue')||prompt.includes('sales')||prompt.includes('revenu')?['revenue']:prompt.includes('cost')||prompt.includes('cout')||prompt.includes('expense')?['cost','unit_cost']:prompt.includes('stock')||prompt.includes('inventory')?['stock']:prompt.includes('duration')||prompt.includes('hours')?['duration']:prompt.includes('budget')?['actual','budget']:[];
 const measure=findField({...p,fields:numeric},question,requestedRoles)||numeric[0],dimension=p.fields.filter(f=>f.kind==='text'&&!['ignore','id','currency'].includes(f.role)).find(f=>prompt.includes(normalize(f.name))||prompt.includes(f.role));
 const clarify=(text:string)=>({...previous,planner:'rules' as const,explanation:text,questions:[text]});if(!measure)return clarify('Choose and confirm a numeric measure first.');if(requestedRoles.length&&!requestedRoles.includes(measure.role)&&!prompt.includes(normalize(measure.name)))return clarify('The requested measure has no confirmed matching definition. Choose it in Add analysis or update preparation.');if(/\b(exclude|excluding|except|without|not|less than|greater than|above|below|top|bottom|last|previous|this)\b/.test(prompt))return clarify('Use the exact filter controls for exclusions, comparisons, relative dates, or ranked requests. This request has not changed the dashboard.');
 if(/\b(remove|hide|delete)\b/.test(prompt)){const selected=previous.cards.filter(c=>prompt.includes(c.tool)||c.measure===measure.id&&prompt.includes(normalize(measure.name)));if(!selected.length)return clarify('Use the remove button on the chart you want to remove.');return {...previous,cards:previous.cards.filter(c=>!selected.includes(c)),planner:'rules',explanation:'Removed the matching charts. Other analyses are unchanged.',questions:[]}}
 const filters:Filter[]=[];const monthNames=['january','february','march','april','may','june','july','august','september','october','november','december'];const month=monthNames.findIndex(m=>new RegExp('\\b'+m+'\\b').test(prompt));if(month>=0)return clarify('Set an on-or-after and on-or-before date filter in the analysis controls for a specific month. No broader period was substituted.');const year=prompt.match(/\b(20\d{2})\b/);if(year&&p.dateField){filters.push({field:p.dateField,op:'gte',value:year[1]+'-01-01'},{field:p.dateField,op:'lte',value:year[1]+'-12-31'})}
 for(const f of p.fields.filter(f=>f.kind==='text'&&f.role!=='id')){const i=Number(f.id.slice(1)),values=[...new Set(t.rows.map(r=>String(r[i]??'').trim()).filter(Boolean))];if(values.length<=100){const match=values.filter(v=>v.length>=2&&new RegExp('(?:^| )'+normalize(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?: |$)').test(prompt));if(match.length===1)filters.push({field:f.id,op:'eq',value:match[0]})}}
 if(/\b(only|filter|where|exclude|excluding)\b/.test(prompt)&&!filters.length)return clarify('Select an exact filter in the analysis controls, or connect AI for more flexible interpretation. No filter was applied.');
 if(/\b(profit|margin)\b/.test(prompt)&&!p.fields.some(f=>f.role==='profit')&&!(/compare|versus| vs /.test(prompt)))return clarify('Net profit or margin needs a confirmed accounting definition. You can compare revenue with a defined cost measure using Compare.');
 let spec:CardSpec;const second=p.fields.filter(f=>f.kind==='number'&&f.id!==measure.id).find(f=>prompt.includes(normalize(f.name))||prompt.includes(f.role));
 if(/forecast|predict|projection/.test(prompt))spec=definition('forecast',measure.id,{horizon:6,filters});else if(/correlat|relationship|scatter/.test(prompt)){if(!second)return clarify('Choose two numeric measures for correlation.');spec=definition('correlation',measure.id,{secondMeasure:second.id,filters})}else if(/ratio|per tonne|per ton|per unit/.test(prompt)){const denominator=second||p.fields.find(f=>f.role==='quantity');if(!denominator)return clarify('Choose an additive quantity denominator and confirm its units.');spec=definition('ratio',measure.id,{secondMeasure:denominator.id,filters})}else if(/compare|versus|\bvs\b|variance/.test(prompt)){const other=second||p.fields.find(f=>f.role==='budget'&&f.id!==measure.id);if(!other)return clarify('Choose a second measure with the same unit for comparison.');spec=definition('comparison',measure.id,{secondMeasure:other.id,filters})}else if(/histogram|distribution|outlier/.test(prompt))spec=definition('distribution',measure.id,{filters});else if(dimension)spec=definition('breakdown',measure.id,{dimension:dimension.id,filters});else if(/month|quarter|year|trend|time/.test(prompt))spec=definition('trend',measure.id,{period:/quarter/.test(prompt)?'quarter':/year|annual/.test(prompt)&&!year?'year':'month',filters});else if(/show|total|average|summary|summari/.test(prompt))spec=definition('summary',measure.id,{filters});else return clarify('Try a measure and an analysis, such as “Monthly revenue”, “Revenue by region”, “Forecast revenue”, or use Add analysis.');
 if(/average|mean/.test(prompt)&&measure.aggregation!=='mean')return clarify(`The confirmed aggregation for ${measure.name} is ${measure.aggregation}. Change its definition to mean before requesting an average.`);
 const check=executeCard(t,p,spec);if(check.status==='blocked')return clarify(check.notes[0]);return {...previous,cards:[...previous.cards,spec].slice(-20),planner:'rules',explanation:`Added ${check.title.toLowerCase()}${filters.length?' with the displayed filters':''}. Existing charts remain on the dashboard.`,questions:[]};
}
export function insights(results:Result[]):string[]{const out:string[]=[];for(const r of results.filter(r=>r.status==='ready')){const fmt=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:2});if(r.tool==='breakdown'&&r.points.length){const total=r.points.reduce((n,p)=>n+(p.value||0),0);if(total>0&&r.points.every(p=>p.value!>=0))out.push(`${r.points[0].name} accounts for ${fmt(r.points[0].value!/total*100)}% of the displayed ${r.title.toLowerCase()}.`)}if(r.tool==='trend'&&r.facts[0])out.push(`${r.title}: the last observed period changed ${fmt(r.facts[0].value*100)}%. Period coverage should be reviewed.`);if(r.tool==='ratio'&&r.value!==null)out.push(`${r.title} is ${fmt(r.value)} ${r.unit}, calculated from matching summed inputs.`);if(r.tool==='comparison'&&r.value!==null)out.push(`${r.title}: the first measure is ${fmt(Math.abs(r.value))} ${r.unit} ${r.value<0?'below':'above'} the second on complete matching rows.`);if(r.tool==='distribution'){const unusual=r.facts.find(f=>f.label.includes('IQR'));if(unusual?.value)out.push(`${r.title} contains ${unusual.value} possible outliers. They remain included.`)}}return out.slice(0,6)}
