import type {Dataset} from '../analytics/analytics';
import type {RawSheet} from '../analytics/import-types';
import type {Table,QualityIssue,Aggregation,Source} from './types';
export const normalize=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
export function columnName(i:number){let out='';for(let n=i+1;n>0;n=Math.floor((n-1)/26))out=String.fromCharCode(65+(n-1)%26)+out;return out}
export function sourceAt(t:Table,row:number,col:number):Source{const address=t.sourceCells?.[row]?.[col];if(address){const split=address.lastIndexOf('!');return {file:t.file,sheet:split<0?t.sheet:address.slice(0,split),cell:split<0?address:address.slice(split+1)}}return {file:t.file,sheet:t.sheet,cell:columnName(t.sourceColumns[col]??col)+(t.sourceRows[row]??row+2)}}
export function prepareTables(book:{name:string;sourceHash:string;datasets:Dataset[];sheets:RawSheet[]}):Table[]{return book.datasets.flatMap((d,index):Table|Table[]=>{
 const raw=book.sheets.find(s=>s.name===(d.provenance?.sheet||d.report?.sheet));
 const issues:QualityIssue[]=(d.report?.issues||[]).slice(0,100).map((i,n)=>({id:'source-'+n,severity:i.severity==='warning'?'warning':'info',message:i.message+(i.source?' Source: '+i.source:''),sources:i.source&&i.source.includes('!')?(i.source.slice(i.source.lastIndexOf('!')+1).match(/[A-Z]+[1-9][0-9]*/g)||[]).slice(0,2).map(cell=>({file:book.name,sheet:i.source!.slice(0,i.source!.lastIndexOf('!')),cell})):[]}));
 const common={id:book.sourceHash.slice(0,18)+'-'+index,name:d.sheet||d.name,file:book.name,sourceHash:book.sourceHash,sheet:d.report?.sheet||d.provenance?.sheet||d.sheet||'Data',currencyEvidence:d.currencyEvidence||{},basis:(d.financial?.basis==='projection'?'plan':d.financial?.basis==='recorded'?'observed':/budget|forecast|projection|plan /i.test(d.name+' '+d.sheet)?'plan':'observed') as Table['basis'],preparation:{originalRows:raw?.originalRows||d.report?.originalRows||d.rows.length,preparedRows:d.rows.length,changes:d.report?.changes||[],issues}};
 if(d.financial&&d.report?.layout==='ledger'){
  const header=raw?.rows.find(r=>r.row===d.report?.headerRow),dateCol=header?.values.findIndex(v=>/^(date|dates)$/.test(normalize(v)))??-1,categoryCol=header?.values.findIndex(v=>/^code interne$|^category$|^categorie$/.test(normalize(v)))??-1;
  return d.financial.metrics.map((metric,mi)=>{let observations=d.rows.filter(r=>r[1]===metric.id);const before=observations.length;
   if(metric.aggregation==='last'){const dates=new Map<string,typeof observations[number]>();for(const row of observations){const previous=dates.get(String(row[0]));const line=(r:typeof row)=>Number(String(r[7]).match(/([0-9]+)$/)?.[1]||0);if(!previous||line(row)>line(previous))dates.set(String(row[0]),row)}observations=[...dates.values()]}
   const headers=['Date','Category',metric.id],rows=observations.map(r=>[r[0],r[3],r[2]]),sourceRows=observations.map(r=>Number(String(r[7]).match(/([0-9]+)$/)?.[1]||1)),sourceColumns=[Math.max(0,dateCol),Math.max(0,categoryCol),0],sourceCells=observations.map((r,i)=>[dateCol>=0?common.sheet+'!'+columnName(dateCol)+sourceRows[i]:'',categoryCol>=0?common.sheet+'!'+columnName(categoryCol)+sourceRows[i]:'',String(r[7])]);
   const unit=metric.currency!=='UNSPECIFIED'?metric.currency:'unspecified',hint={unit,aggregation:metric.aggregation,...(metric.aggregation==='last'?{role:'balance' as const}:{role:'measure' as const})};return {...common,id:common.id+'-ledger-'+mi,name:common.sheet+' · '+metric.label,headers,rows,sourceRows,sourceColumns,sourceCells,metricHints:{[metric.id]:hint},currencyEvidence:unit==='unspecified'?{}:{[metric.id]:[unit]},preparation:{...common.preparation,preparedRows:rows.length,changes:[...common.preparation.changes,'Separated each ledger measure and currency; cash flows are not labeled revenue or operating expenses.',...(before!==rows.length?['Retained the last source-row balance for each date. Earlier intraday running balances are not added together.']:[])],issues:[...common.preparation.issues,...(metric.aggregation==='last'?[{id:'ledger-order',severity:'warning' as const,message:'End-of-day balances use ledger row order. Confirm the source is chronological within each date.',sources:[]}]:[])]}};
  }).filter(t=>t.rows.length>0);
 }
 if(d.financial){
  const metrics=d.financial.metrics.filter(m=>d.rows.some(r=>r[1]===m.id&&r[6]!=='Unconfirmed template period'));
  if(metrics.length>149)throw new Error('This financial matrix has too many measures for one dashboard. Select a smaller source table.');
  const periods=[...new Set(d.rows.filter(r=>r[6]!=='Unconfirmed template period').map(r=>String(r[0])))].sort(),headers=['Period',...metrics.map(m=>m.id)],rows:Table['rows']=[],sourceCells:string[][]=[];
  for(const period of periods){const values:Table['rows'][number]=[period],sources=[''];for(const metric of metrics){const candidates=d.rows.filter(r=>String(r[0])===period&&r[1]===metric.id&&r[6]!=='Unconfirmed template period');if(candidates.length>1)throw new Error('A financial measure has multiple observations in one period. Resolve the scope before creating a general dashboard.');values.push(candidates[0]?.[2]??null);sources.push(String(candidates[0]?.[7]||''))}const first=sources.find(Boolean);if(first){const m=first.match(/!([A-Z]+)[0-9]+$/);if(m)sources[0]=common.sheet+'!'+m[1]+(d.report?.headerRow||1)}rows.push(values);sourceCells.push(sources)}
  const metricHints:NonNullable<Table['metricHints']>={},currencyEvidence:Table['currencyEvidence']={};for(const m of metrics){metricHints[m.id]={unit:m.currency!=='UNSPECIFIED'?m.currency:m.unit==='percent'?'percent':'unspecified',aggregation:m.aggregation==='last'?'last' as Aggregation:'sum',...(m.role==='balance'||m.role==='opening'?{role:'balance' as const}:{})};if(m.currency!=='UNSPECIFIED')currencyEvidence[m.id]=[m.currency]}
  return {...common,headers,rows,sourceRows:periods.map((_,i)=>i+1),sourceColumns:headers.map((_,i)=>i),sourceCells,metricHints,currencyEvidence,preparation:{...common.preparation,preparedRows:rows.length,changes:[...common.preparation.changes,'Reshaped the financial matrix into one row per period and one column per measure; original value cells retained.']}};
 }
 const sourceRows=d.provenance?.rows||d.rows.map((_,i)=>i+2),sourceColumns=d.provenance?.columns||d.headers.map((_,i)=>i),byRow=new Map(raw?.rows.map(r=>[r.row,r])||[]);
 const rows=d.rows.map((row,i)=>row.map((v,c)=>{const original=byRow.get(sourceRows[i])?.values[sourceColumns[c]];return typeof original==='string'?original.trim():original===undefined?v:original}));
 const scenario=d.headers.findIndex(h=>/^(scenario|basis|data type|type de donnees)$/.test(normalize(h)));let basis=common.basis;if(scenario>=0){const values=[...new Set(rows.map(r=>normalize(r[scenario])).filter(Boolean))];const plans=values.some(v=>/budget|plan|forecast|projection|prevision/.test(v)),actuals=values.some(v=>/actual|observed|recorded|realise|reel/.test(v));basis=plans&&actuals?'mixed':plans?'plan':actuals?'observed':'unspecified'}return {...common,headers:d.headers,rows,sourceRows,sourceColumns,basis};
 }).filter(t=>t.rows.length>0&&t.headers.length>1)}
