import type {Table,Field,Profile,Role,Aggregation,Definitions,QualityIssue} from './types';import {normalize,sourceAt} from './prepare';import {parseDate} from '../analytics/analytics';
const datePattern=/^(date|order date|invoice date|transaction date|sale date|snapshot date|period|periode|mois|month|year|annee|timestamp|jour|day)$/;
const roles:[Role,RegExp][]=[['date',datePattern],['currency',/^(currency|devise|monnaie|currency code)$/],['id',/\bid$|^id\b|invoice number|order number|sku|code article|postal code|zip code|postcode/],['customer',/customer|client|buyer/],['region',/region|territory|market|country|pays|warehouse|entrepot|location|site|zone/],['product',/product|produit|item|article/],['reorder',/reorder|stock minimum|safety stock/],['stock',/stock|inventory|on hand|onhand/],['balance',/balance|solde|cash balance|opening cash|closing cash/],['unit_price',/unit price|prix unitaire|selling price/],['unit_cost',/unit cost|cout unitaire|cost per/],['budget',/budget|planned amount|montant prevu/],['actual',/^actual|realise|recorded amount/],['profit',/^(profit|net profit|gross profit|benefice|resultat net)$/],['revenue',/^(revenue|revenues|net revenue|gross revenue|sales|net sales|gross sales|sales total|total sales|revenu|revenus|revenues bruts|chiffre d affaires|ca net|turnover|sales revenue)( usd| eur| gbp| cdf)?$/],['cost',/^(cost|costs|expenses|expense|opex|cogs|cost of goods sold|cout|couts|depenses|operating cost|total cost|total opex|sous total opex|total depenses opex)( usd| eur| gbp| cdf)?$/],['quantity',/quantity|quantite|units sold|units produced|inspected units|production|tonnes|volume|output|defects|defect count|ffb|cpo/],['duration',/duration|hours|minutes|time taken|downtime|lead time|heures|temps/],['rating',/rating|score|satisfaction/],['category',/category|categorie|department|departement|account|compte|scenario|status|type/]];
const monetary=new Set<Role>(['revenue','cost','profit','unit_price','unit_cost','budget','actual','balance']);
const numericRoles=new Set<Role>([...monetary,'quantity','stock','reorder','duration','rating','measure']);
export function rawNumber(value:unknown,format:Field['numberFormat']='auto'):{value:number|null;ambiguous:boolean}{
 if(typeof value==='number')return {value:Number.isFinite(value)?value:null,ambiguous:false};if(value==null||String(value).trim()==='')return {value:null,ambiguous:false};let s=String(value).trim();const percentage=s.endsWith('%');const negative=/^\(.*\)$/.test(s);s=s.replace(/[()]/g,'').replace(/\b(?:USD|EUR|GBP|CDF|CAD|AUD|XOF|XAF|FC|US)\b/gi,'').replace(/[$€£%\s\u00a0\u202f']/g,'');if(!/^[-+]?\d[\d.,]*$/.test(s))return {value:null,ambiguous:false};
 const ambiguous=/^[+-]?[1-9]\d{0,2}[.,]\d{3}$/.test(s)&&format==='auto';if(ambiguous)return {value:null,ambiguous:true};
 if(format==='dot'){if(s.includes(',')&&!/^[+-]?\d{1,3}(,\d{3})*(\.\d+)?$/.test(s))return {value:null,ambiguous:false};s=s.replace(/,/g,'')}
 else if(format==='comma'){if(s.includes('.')&&!/^[+-]?\d{1,3}(\.\d{3})*(,\d+)?$/.test(s))return {value:null,ambiguous:false};s=s.replace(/\./g,'').replace(',','.')}
 else if(s.includes('.')&&s.includes(',')){s=s.lastIndexOf('.')>s.lastIndexOf(',')?s.replace(/,/g,''):s.replace(/\./g,'').replace(',','.')}
 else if((s.match(/,/g)||[]).length>1){if(!/^[+-]?\d{1,3}(,\d{3})+$/.test(s))return {value:null,ambiguous:false};s=s.replace(/,/g,'')}
 else if((s.match(/\./g)||[]).length>1){if(!/^[+-]?\d{1,3}(\.\d{3})+$/.test(s))return {value:null,ambiguous:false};s=s.replace(/\./g,'')}
 else s=s.replace(',','.');const n=Number(s)*(negative?-1:1)/(percentage?100:1);return {value:Number.isFinite(n)?n:null,ambiguous:false};
}
export function dateValue(value:unknown,f:Pick<Field,'name'|'dateFormat'>){if(value==null)return null;const s=String(value).trim();if(/^\d{4}$/.test(s)&&/year|annee|period|periode/i.test(f.name))return parseDate(s);const slash=s.match(/^(\d{1,2})[/-](\d{1,2})[/-]\d{4}$/);if(slash&&f.dateFormat==='auto'){if(+slash[1]<=12&&+slash[2]<=12)return null;return parseDate(s,+slash[1]>12?'DMY':'MDY')}return parseDate(value as string|number,f.dateFormat==='DMY'?'DMY':'MDY')}
export function isAmbiguousDate(v:unknown){const m=String(v??'').match(/^(\d{1,2})[/-](\d{1,2})[/-]\d{4}$/);return !!m&&+m[1]<=12&&+m[2]<=12}
export function fieldValue(v:unknown,f:Field){return f.kind==='number'?rawNumber(v,f.numberFormat).value:f.kind==='date'?dateValue(v,f):v==null||String(v).trim()===''?null:String(v).trim()}
export function expectedAggregation(role:Role):Aggregation{return ['balance','stock','reorder'].includes(role)?'last':['rating','duration','unit_price','unit_cost','measure'].includes(role)?'mean':numericRoles.has(role)?'sum':role==='id'?'count':'none'}
function inferredUnit(header:string,role:Role,evidence:string[],values:unknown[]){const h=normalize(header);const codes=[...new Set([...evidence,...(header.toUpperCase().match(/\b(?:USD|EUR|GBP|CDF|CAD|AUD|XOF|XAF)\b/g)||[])])];if(codes.length===1&&codes[0]!=='DOLLAR')return codes[0];if(/\bkg\b|kilogram/.test(h))return 'kg';if(/tonne|\btons?\b/.test(h))return 't';if(/hour|heures?|\bhr\b/.test(h))return 'hours';if(/minute|\bmin\b/.test(h))return 'minutes';if(values.some(v=>typeof v==='string'&&v.includes('%')))return 'percent';if(['quantity','stock','reorder'].includes(role))return 'units';if(role==='rating')return 'score';return 'unspecified'}
export async function inferProfile(table:Table,remembered?:Definitions):Promise<Profile>{
 const fields:Field[]=table.headers.map((name,c)=>{const present=table.rows.map(r=>r[c]).filter(v=>v!==null&&String(v).trim()!==''),parsed=present.map(v=>rawNumber(v)),header=normalize(name),hint=table.metricHints?.[name];let role=hint?.role||roles.find(([,p])=>p.test(header))?.[0]||'dimension';const dateFraction=present.filter(v=>/^\d{4}-\d{1,2}(?:-\d{1,2})?/.test(String(v))||isAmbiguousDate(v)).length/Math.max(1,present.length),numericFraction=parsed.filter(v=>v.value!==null||v.ambiguous).length/Math.max(1,present.length);let kind:Field['kind']=role==='id'?'text':role==='date'?'date':numericFraction>=.7?'number':dateFraction>=.8&&role==='dimension'?'date':'text';if(kind==='date')role='date';if(kind==='number'&&role==='dimension')role='measure';if(kind==='text'&&numericRoles.has(role))role='dimension';
  const codes=table.currencyEvidence[name]||[],unit=hint?.unit||inferredUnit(name,role,codes,present),aggregation=hint?.aggregation||expectedAggregation(role),known=!['measure','dimension'].includes(role);return {id:'c'+c,name,kind,role,unit,aggregation,dateFormat:'auto',numberFormat:'auto',confidence:known?.9:.45,definition:known?name:'Confirm the business meaning of this column.',origin:'detected',missing:table.rows.length-present.length,invalid:0,unique:new Set(present.map(String)).size,min:null,max:null,ambiguous:0} as Field});
 const signature=JSON.stringify(fields.map(f=>({name:normalize(f.name),kind:f.kind,unit:f.unit})));const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(signature));const fingerprint=[...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('');
 let domain:Profile['domain']=fields.some(f=>f.role==='stock')?'inventory':fields.some(f=>f.role==='revenue')&&fields.some(f=>['customer','product'].includes(f.role))?'sales':fields.some(f=>['budget','actual','balance'].includes(f.role))||table.metricHints?'finance':fields.some(f=>f.role==='duration')||fields.some(f=>f.role==='quantity')&&fields.some(f=>f.role==='cost')?'operations':'general';
 let p:Profile={version:1,fingerprint,domain,grain:domain==='inventory'?'snapshot':table.metricHints?'period':domain==='sales'?'transaction':'record',fields,dateField:fields.find(f=>f.kind==='date')?.id||'',currencyField:fields.find(f=>f.role==='currency')?.id||'',entityKeys:fields.filter(f=>['product','region'].includes(f.role)||domain==='inventory'&&f.role==='id').slice(0,3).map(f=>f.id),deduplicate:false,excludeTotals:true,basis:table.basis,confirmed:false,issues:[]};
 if(remembered?.fingerprint===fingerprint&&remembered.fields.length===fields.length&&remembered.fields.every((f,i)=>normalize(f.name)===normalize(fields[i].name)&&f.kind===fields[i].kind)){p={...p,domain:remembered.domain,grain:remembered.grain,basis:remembered.basis,dateField:remembered.dateField,currencyField:remembered.currencyField,entityKeys:remembered.entityKeys,fields:fields.map((f,i)=>({...f,...remembered.fields[i],origin:'remembered'}))}}
 return validateProfile(table,p);
}
export function validateProfile(table:Table,input:Profile):Profile{
 const issues:QualityIssue[]=[...table.preparation.issues];const fields=input.fields.map((f,c)=>{const values=table.rows.map(r=>r[c]),present=values.filter(v=>v!==null&&String(v).trim()!==''),parsed=present.map(v=>fieldValue(v,f)),valid=parsed.filter(v=>v!==null),numeric=valid.filter((v):v is number=>typeof v==='number'),ambiguous=f.kind==='number'?present.filter(v=>rawNumber(v,f.numberFormat).ambiguous).length:f.kind==='date'&&f.dateFormat==='auto'?present.filter(isAmbiguousDate).length:0;
  const updated={...f,missing:values.length-present.length,invalid:present.length-valid.length,unique:new Set(valid.map(String)).size,min:numeric.length?Math.min(...numeric):null,max:numeric.length?Math.max(...numeric):null,ambiguous};
  if(ambiguous)issues.push({id:'ambiguous-'+f.id,severity:'review',field:f.id,count:ambiguous,message:`${f.name}: choose the ${f.kind==='date'?'day/month order':'decimal convention'} before using these values.`,sources:values.flatMap((v,r)=>(f.kind==='date'?isAmbiguousDate(v):rawNumber(v).ambiguous)?[sourceAt(table,r,c)]:[]).slice(0,5)});
  if(updated.invalid>ambiguous)issues.push({id:'invalid-'+f.id,severity:f.origin==='remembered'?'review':'warning',field:f.id,count:updated.invalid,message:`${f.name}: ${updated.invalid} values cannot be read as ${f.kind}s. They remain missing in calculations.`,sources:[]});
  const codes=table.currencyEvidence[f.name]||[];if(monetary.has(f.role)&&f.unit==='unspecified'&&!input.currencyField)issues.push({id:'currency-'+f.id,severity:'review',field:f.id,message:`Confirm the currency for ${f.name}.`,sources:[]});if(codes.some(c=>c!=='DOLLAR'&&f.unit!=='unspecified'&&c!==f.unit))issues.push({id:'currency-conflict-'+f.id,severity:'review',field:f.id,message:`${f.name}: the chosen unit conflicts with the source currency evidence. Separate currencies before combining values.`,sources:[]});
  if(f.kind==='number'&&['stock','balance','reorder'].includes(f.role)&&f.aggregation!=='last')issues.push({id:'snapshot-'+f.id,severity:'review',field:f.id,message:`${f.name} is a snapshot measure. Use latest-period aggregation to avoid adding balances across dates.`,sources:[]});
  if(f.kind==='number'&&f.aggregation==='last'&&!input.dateField)issues.push({id:'snapshot-date-'+f.id,severity:'review',field:f.id,message:`Choose a date field to determine the latest ${f.name} snapshot.`,sources:[]});
  if(f.kind==='number'&&f.unit==='percent'&&numeric.some(v=>Math.abs(v)>1))issues.push({id:'percent-scale-'+f.id,severity:'review',field:f.id,message:`${f.name}: percentage values must be decimal shares or include %. Confirm the source scale.`,sources:[]});
  return updated;
 });
 const duplicates=table.rows.length-new Set(table.rows.map(r=>JSON.stringify(r))).size;if(duplicates)issues.push({id:'duplicates',severity:'warning',count:duplicates,message:`${duplicates} exact duplicate rows detected. ${input.deduplicate?'Duplicate copies will be excluded.':'They are retained until you choose to exclude them.'}`,sources:[]});
 const totalCount=table.rows.filter(r=>r.some(v=>typeof v==='string'&&/^(grand total|sub[ -]?total|sous[ -]?total|total general|total)$/i.test(v.trim()))).length;if(totalCount)issues.push({id:'total-rows',severity:'warning',count:totalCount,message:`${totalCount} explicitly labeled total/subtotal rows ${input.excludeTotals?'will be excluded from detail analysis':'are included; check for double-counting'}.`,sources:[]});
 if(input.basis!=='observed')issues.push({id:'basis',severity:'info',message:'This table is not confirmed as observed history. Historical forecasting is unavailable; use the financial scenario workspace for plans.',sources:[]});
 return {...input,fields,issues};
}
export function definitionsFor(p:Profile):Definitions{return {fingerprint:p.fingerprint,domain:p.domain,grain:p.grain,fields:p.fields.map(({name,kind,role,unit,aggregation,dateFormat,numberFormat,definition})=>({name,kind,role,unit,aggregation,dateFormat,numberFormat,definition})),dateField:p.dateField,currencyField:p.currencyField,entityKeys:p.entityKeys,basis:p.basis}}
export {monetary,numericRoles};
