import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,BarChart3,Building2,Check,ChevronRight,Download,FileCheck2,Globe2,Layers3,RotateCcw,SlidersHorizontal,Upload,AlertTriangle,ArrowRight,Search} from 'lucide-react';
import {LumniaLogo} from '../components/branding/LumniaBrand';
import {EXAMPLE_CSV,prepare,summarize,grouped,scenario,money,pct,toCSV} from '../lib/public-finance/model.js';
import './public-finance.css';
const TABS=[['overview','Vue d’ensemble',BarChart3],['budget','Exécution budgétaire',Building2],['delivery','Programmes & résultats',Layers3],['quality','Sources & préparation',FileCheck2],['scenario','Scénarios',SlidersHorizontal],['citizen','Vue citoyenne',Globe2]];
const KEY='lumnia.public-finance-demo.v1';
function download(name,body,type='text/csv;charset=utf-8'){const u=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Meter({value,label,tone=''}){return <div className={'pf-meter '+tone} role="img" aria-label={label+' : '+pct(value)}><span style={{width:Math.min(100,Math.max(0,value*100))+'%'}}/></div>;}
function Stat({label,value,note}){return <article className="pf-stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;}
function Breakdown({rows,by}){return <div className="pf-breakdown">{grouped(rows,by).map(r=><div key={r.name}><div className="pf-between"><strong>{r.name}</strong><span>{pct(r.execution)}</span></div><Meter value={r.execution} label={r.name}/><div className="pf-between pf-muted"><small>{money(r.paye)} payés</small><small>{money(r.budget)} votés</small></div></div>)}</div>;}
export default function PublicFinanceDemo(){
 const [tab,setTab]=useState('overview'),[dataset,setDataset]=useState(()=>prepare(EXAMPLE_CSV)),[filename,setFilename]=useState('budget_illustratif_S1_2026.csv'),[institution,setInstitution]=useState('Toutes'),[province,setProvince]=useState('Toutes'),[notice,setNotice]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(null),[cost,setCost]=useState(10),[funding,setFunding]=useState(0),[query,setQuery]=useState(''),[answer,setAnswer]=useState(''),[detail,setDetail]=useState(null),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
 const fileRef=useRef(null),dialogRef=useRef(null);
 useEffect(()=>{const title=document.title;document.title='Lumnia · Finances publiques — Démo';try{setSaved(!!localStorage.getItem(KEY));}catch{}return()=>{document.title=title;};},[]);
 useEffect(()=>{if(detail)dialogRef.current?.showModal();},[detail]);
 const rows=useMemo(()=>dataset.rows.filter(r=>(institution==='Toutes'||r.institution===institution)&&(province==='Toutes'||r.province===province)),[dataset,institution,province]);
 const totals=summarize(rows), projection=scenario(rows,cost,funding), institutions=[...new Set(dataset.rows.map(r=>r.institution))],provinces=[...new Set(dataset.rows.map(r=>r.province))];
 function reset(){setDataset(prepare(EXAMPLE_CSV));setFilename('budget_illustratif_S1_2026.csv');setInstitution('Toutes');setProvince('Toutes');setCost(10);setFunding(0);setPreview(null);setError('');setAnswer('');setNotice('Exemple réinitialisé. Votre sauvegarde locale est conservée.');}
 async function upload(event){const f=event.target.files?.[0];event.target.value='';if(!f)return;setError('');setBusy(true);try{if(!/\.csv$/i.test(f.name))throw Error('Utilisez un CSV UTF-8. Le modèle est téléchargeable dans Sources & préparation.');if(f.size>2*1024*1024)throw Error('Limite de cette démo : 2 Mo.');const text=await f.text(),data=prepare(text);if(!data.rows.length)throw Error('Aucune ligne exploitable. Corrigez les données avant de réessayer.');setPreview({data,name:f.name});setTab('quality');setNotice('Import préparé. Vérifiez les exclusions avant de l’appliquer.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,text:toCSV(dataset.source.map(r=>r.raw)),filename,institution,province,cost,funding}));setSaved(true);setNotice('Revue enregistrée dans ce navigateur uniquement.');}catch{setError('Sauvegarde locale indisponible ou espace insuffisant.');}}
 function reopen(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.version!==1)throw Error('Sauvegarde incompatible.');const next=prepare(s.text);if(!next.rows.length)throw Error('Sauvegarde sans données exploitables.');setDataset(next);setFilename(s.filename);setInstitution(s.institution);setProvince(s.province);setCost(Number.isFinite(s.cost)?s.cost:10);setFunding(Number.isFinite(s.funding)?s.funding:0);setPreview(null);setAnswer('');setError('');setNotice('Revue locale rouverte.');}catch(e){setError('Impossible de rouvrir la revue : '+e.message);}}
 function ask(value){setQuery('');setAnswer('');const q=value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(/retard/.test(q)){setTab('delivery');setAnswer(`${totals.late} programme(s) ont une échéance avant le 1er juillet 2026 et une cible non atteinte dans la sélection. Consultez chaque fiche avant d’en attribuer la cause.`);}else if(/province|region/.test(q)){setTab('budget');setAnswer('Les paiements par province sont affichés sous la ventilation par institution. Les filtres restent actifs.');}else if(/10|cout|scenario/.test(q)){setCost(10);setTab('scenario');setAnswer('Hausse de 10 % appliquée au budget restant à dépenser, sans modifier les paiements déjà observés.');}else if(/source|qualite|donnee/.test(q)){setTab('quality');setAnswer(`${dataset.rows.length} lignes retenues ; ${dataset.issues.length} lignes exclues. Consultez les motifs et les valeurs brutes.`);}else if(/budget|execution|depens|paye/.test(q)){setTab('budget');setAnswer(`${money(totals.paye)} payés sur ${money(totals.budget)} votés, soit ${pct(totals.execution)} dans la sélection.`);}else setAnswer('Cette démo comprend les questions sur les dépenses, les provinces, les retards, les sources et le scénario +10 %. Essayez une des suggestions.');}
 function exportCitizen(){const data=grouped(rows,'institution');const csv='\uFEFFDÉMONSTRATION — données non officielles ; S1 2026 ; USD\nInstitution;Budget voté;Paiements;Taux de paiement\n'+data.map(r=>['"'+r.name.replace(/"/g,'""').replace(/^[=+@\-]/,"'$&")+'"',r.budget,r.paye,(r.execution*100).toFixed(1)+'%'].join(';')).join('\n');download('extrait_citoyen_DEMO.csv',csv);setNotice('Extrait agrégé téléchargé. Aucun rapport n’a été publié en ligne.');}
 const quality=preview?.data||dataset;
 return <div className="pf-app" lang="fr"><a className="pf-skip" href="#pf-content" onClick={e=>{e.preventDefault();document.getElementById('pf-content')?.focus();}}>Aller au contenu</a><aside className="pf-sidebar"><a href="/" aria-label="Accueil Lumnia"><LumniaLogo/></a><div className="pf-workspace"><span className="pf-light"/><div>Finances publiques<small>Espace de démonstration</small></div></div><span className="pf-eyebrow">PILOTAGE & IMPACT</span><nav aria-label="Sections de la démonstration">{TABS.map(([id,label,Icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><Icon size={18}/>{label}{id==='quality'&&dataset.issues.length>0&&<span className="pf-count">{dataset.issues.length}</span>}</button>)}</nav><div className="pf-sidebar-bottom"><p>Light where there’s none.</p><a href="#/demo">Voir la démo entreprise <ArrowUpRight size={15}/></a><small>Une proposition Lumnia.<br/>Sans affiliation gouvernementale.</small></div></aside>
 <div className="pf-main"><header className="pf-top"><span>Lumnia <ChevronRight size={14}/> Secteur public <span className="pf-demo-pill">DÉMO INTERACTIVE</span></span><div><button onClick={reopen} disabled={!saved}>Rouvrir</button><button onClick={save}>Enregistrer localement</button></div></header><main id="pf-content" tabIndex={-1}><div className="pf-heading"><div><p className="pf-eyebrow">RDC · CONCEPT DE PILOTAGE BUDGÉTAIRE</p><h1>Du budget à l’impact.</h1><p>Une vision partagée des ressources, des programmes et des résultats.</p></div><button className="pf-primary" onClick={()=>fileRef.current?.click()} disabled={busy}><Upload size={17}/>{busy?'Préparation…':'Importer un CSV'}</button><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={upload} hidden/></div>
 <div className="pf-disclosure"><span><span className="pf-dot"/> DONNÉES SYNTHÉTIQUES</span><p>Proposition inspirée des besoins évoqués autour du PSEN 2026–2030. Chiffres, institutions et programmes illustratifs ; aucun résultat officiel. Imports traités dans votre navigateur.</p><button onClick={reset} aria-label="Réinitialiser la démonstration"><RotateCcw size={16}/><span>Réinitialiser</span></button></div>
 {notice&&<p className="pf-notice" role="status"><Check size={16}/>{notice}<button onClick={()=>setNotice('')} aria-label="Fermer la notification">×</button></p>}{error&&<p className="pf-error" role="alert">{error}</p>}
 <div className="pf-filterbar"><div><span className="pf-eyebrow">PÉRIMÈTRE</span><strong>1er semestre 2026</strong><small>Situation au 30 juin · USD</small></div><label>Institution<select value={institution} onChange={e=>{setInstitution(e.target.value);setAnswer('');}}><option>Toutes</option>{institutions.map(i=><option key={i}>{i}</option>)}</select></label><label>Province<select value={province} onChange={e=>{setProvince(e.target.value);setAnswer('');}}><option>Toutes</option>{provinces.map(i=><option key={i}>{i}</option>)}</select></label><span className="pf-filter-count">{rows.length} programmes retenus</span></div>
 <div className="pf-section-title"><h2>{TABS.find(t=>t[0]===tab)[1]}</h2><span>01—06 / {String(TABS.findIndex(t=>t[0]===tab)+1).padStart(2,'0')}</span></div>
 {!rows.length&&<div className="pf-empty"><h3>Aucun programme dans cette sélection</h3><p>Changez les filtres pour retrouver vos données.</p><button onClick={()=>{setInstitution('Toutes');setProvince('Toutes');}}>Effacer les filtres</button></div>}
 {rows.length>0&&<>
 {['overview','budget','citizen'].includes(tab)&&<div className="pf-stats"><Stat label="Budget voté · annuel" value={money(totals.budget)} note="Somme des lignes retenues"/><Stat label="Paiements · à fin juin" value={money(totals.paye)} note={`${pct(totals.execution)} du budget annuel`}/><Stat label="Engagements · à fin juin" value={money(totals.engage)} note="Incluent les montants déjà payés"/><Stat label="Programmes en retard" value={totals.late+' / '+rows.length} note="Échéance passée, cible non atteinte"/></div>}
 {tab==='overview'&&<><div className="pf-grid"><section className="pf-card"><div className="pf-between"><div><p className="pf-eyebrow">RESSOURCES MOBILISÉES</p><h3>Où en est l’exécution ?</h3></div><button className="pf-link" onClick={()=>setTab('budget')}>Détailler <ArrowUpRight size={16}/></button></div><p className="pf-muted">Paiements à fin juin / budget annuel, par institution.</p><Breakdown rows={rows} by="institution"/><div className="pf-card-note">Un faible taux de paiement ne prouve pas un retard : le calendrier de décaissement doit être confirmé.</div></section><section className="pf-card pf-decision"><p className="pf-eyebrow">À L’ORDRE DU JOUR</p><h3>Les décisions à préparer.</h3><button onClick={()=>setTab('delivery')}><span>01</span><div><strong>{totals.late} programmes à examiner</strong><p>Une échéance passée avec une cible encore non atteinte.</p></div><ArrowRight size={18}/></button><button onClick={()=>setTab('quality')}><span>02</span><div><strong>{dataset.issues.length} lignes exclues du calcul</strong><p>Vérifier les doublons et données manquantes avant consolidation.</p></div><ArrowRight size={18}/></button><button onClick={()=>setTab('scenario')}><span>03</span><div><strong>Anticiper une hausse des coûts</strong><p>Tester +10 % sur les dépenses restantes et mesurer le besoin de financement.</p></div><ArrowRight size={18}/></button></section></div><section className="pf-card pf-journey"><div><p className="pf-eyebrow">UNE CHAÎNE DE CONFIANCE</p><h3>Chaque résultat garde sa source.</h3></div><div><span>01 · Collecter</span><ArrowRight size={16}/><span>02 · Vérifier</span><ArrowRight size={16}/><span>03 · Décider</span><ArrowRight size={16}/><span>04 · Expliquer</span></div><button onClick={()=>setTab('quality')}>Voir la préparation <ArrowUpRight size={16}/></button></section></>}
 {tab==='budget'&&<><div className="pf-grid"><section className="pf-card"><h3>Par institution</h3><Breakdown rows={rows} by="institution"/></section><section className="pf-card"><h3>Par province</h3><Breakdown rows={rows} by="province"/></section></div><section className="pf-card"><h3>Du crédit voté au paiement</h3><p className="pf-muted">Les paiements sont inclus dans les engagements : ces montants ne s’additionnent pas.</p><div className="pf-table-wrap"><table><thead><tr><th>Programme</th><th>Voté annuel</th><th>Engagé</th><th>Payé</th><th>Non engagé</th><th>Source</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><th>{r.programme}<small>{r.institution}</small></th><td>{money(r.budget)}</td><td>{money(r.engage)}</td><td>{money(r.paye)}</td><td>{money(r.budget-r.engage)}</td><td><button onClick={()=>setDetail(r)}>Ligne {r.sourceRow} ↗</button></td></tr>)}</tbody></table></div></section></>}
 {tab==='delivery'&&<><div className="pf-info"><AlertTriangle size={19}/><span>Les cibles ont des unités propres à chaque programme. Nous comparons les pourcentages ; nous n’additionnons pas des écoles et des agents formés. « En retard » = échéance avant le 1er juillet et cible non atteinte.</span></div><div className="pf-programmes">{rows.map(r=><article className="pf-card" key={r.id}><div className="pf-between"><span className="pf-eyebrow">{r.id} · {r.province}</span><span className={'pf-badge '+(r.echeance<'2026-07-01'&&r.realise<r.cible?'warning':'')}>{r.echeance<'2026-07-01'&&r.realise<r.cible?'En retard':'À suivre'}</span></div><h3>{r.programme}</h3><p className="pf-muted">{r.institution}</p><div className="pf-between"><span>Cible atteinte</span><strong>{r.realise} / {r.cible}</strong></div><Meter value={r.realise/r.cible} label="Cible atteinte" tone="teal"/><div className="pf-between"><small>Paiement : {pct(r.paye/r.budget)}</small><small>Échéance : {r.echeance}</small></div><button className="pf-link" onClick={()=>setDetail(r)}>Examiner la fiche source <ArrowUpRight size={15}/></button></article>)}</div></>}
 {tab==='scenario'&&<><div className="pf-grid pf-scenario"><section className="pf-card"><p className="pf-eyebrow">HYPOTHÈSES MODIFIABLES</p><h3>Si les coûts évoluent…</h3><p>Le modèle part du budget annuel et des paiements observés. Ce n’est pas une prévision statistique.</p><label className="pf-range">Coût des dépenses restantes <strong>{cost>0?'+':''}{cost} %</strong><input type="range" min="-30" max="50" step="1" value={cost} onChange={e=>setCost(+e.target.value)}/></label><label className="pf-range">Variation du financement disponible <strong>{funding>0?'+':''}{funding} %</strong><input type="range" min="-30" max="30" step="1" value={funding} onChange={e=>setFunding(+e.target.value)}/></label><button onClick={()=>{setCost(0);setFunding(0);}}>Revenir au budget initial</button></section><section className="pf-card pf-scenario-result"><p className="pf-eyebrow">BESOIN COMPLÉMENTAIRE ESTIMÉ</p><strong>{money(projection.gap)}</strong><p>{projection.gap?'À financer pour couvrir les dépenses du scénario.':'Le financement du scénario couvre les dépenses estimées.'}</p><dl><div><dt>Dépenses du scénario</dt><dd>{money(projection.estimate)}</dd></div><div><dt>Financement supposé</dt><dd>{money(projection.funding)}</dd></div><div><dt>Déjà payé · inchangé</dt><dd>{money(totals.paye)}</dd></div></dl></section></div><section className="pf-card"><h3>Une hypothèse lisible, un calcul vérifiable.</h3><p>Dépenses estimées = payé + (budget voté − payé) × (1 + variation des coûts).</p><p className="pf-muted">Le budget voté est utilisé comme hypothèse de financement, pas comme preuve de trésorerie disponible. Aucune saisonnalité, probabilité, incidence de change ou contrainte de passation de marchés n’est modélisée. Le scénario ne modifie pas les données sources.</p></section></>}
 {tab==='citizen'&&<section className="pf-card pf-citizen"><p className="pf-eyebrow">APERÇU D’UNE RESTITUTION PUBLIQUE</p><h3>Comprendre l’utilisation des ressources.</h3><p>Sur un budget illustratif de <strong>{money(totals.budget)}</strong>, <strong>{money(totals.paye)}</strong> ont été payés au premier semestre, soit <strong>{pct(totals.execution)}</strong>. Le périmètre couvre {rows.length} programmes dans la sélection.</p><Breakdown rows={rows} by="institution"/><div className="pf-info">Données de démonstration, non auditées. L’extrait téléchargeable contient uniquement les agrégats affichés. Il ne publie aucune donnée en ligne. Les lignes exclues sont hors totaux : {dataset.issues.length} sur {dataset.source.length} lignes du fichier.</div><button className="pf-primary" onClick={exportCitizen}><Download size={16}/>Télécharger l’extrait citoyen</button></section>}
 </>}
 {tab==='quality'&&<><section className="pf-card"><div className="pf-between"><div><p className="pf-eyebrow">{preview?'IMPORT EN ATTENTE':'SOURCE ACTIVE'}</p><h3>{preview?.name||filename}</h3></div><button onClick={()=>download('modele_budget_illustratif.csv',EXAMPLE_CSV)}><Download size={16}/>Modèle CSV</button></div><p>USD · budget annuel 2026 · engagements et paiements cumulés au 30 juin. Seuls les fichiers de ce périmètre sont pris en charge par cette démo.</p><div className="pf-stats"><Stat label="Lignes reçues" value={quality.source.length} note="Hors en-tête"/><Stat label="Lignes exploitables" value={quality.rows.length} note="Retenues après contrôles"/><Stat label="Lignes exclues" value={quality.issues.length} note="À corriger dans le fichier"/><Stat label="Valeurs normalisées" value={quality.normalized} note="Espaces et séparateurs numériques"/></div><div className="pf-info">Les exclusions sont signalées ; elles ne sont jamais remplacées par zéro. Les doublons sont détectés par identifiant. Le premier enregistrement est conservé s’il est valide. Aucun rapprochement automatique entre institutions n’est supposé.</div>{preview&&<div className="pf-actions"><button className="pf-primary" onClick={()=>{setDataset(preview.data);setFilename(preview.name);setPreview(null);setInstitution('Toutes');setProvince('Toutes');setAnswer('');setNotice('Import appliqué avec les exclusions affichées.');}}>Appliquer {preview.data.rows.length} lignes retenues</button><button onClick={()=>{setPreview(null);setNotice('Import annulé. Les données actives sont conservées.');}}>Annuler l’import</button></div>}</section><section className="pf-card"><h3>Points à corriger</h3>{quality.issues.length===0?<p>Aucune anomalie détectée par les contrôles de cette démo. Cela ne constitue pas un audit.</p>:quality.issues.map(i=><article className="pf-issue" key={i.sourceRow}><AlertTriangle size={18}/><div><strong>Ligne {i.sourceRow} · {i.id}</strong><p>{i.reasons.join(' · ')}</p><details><summary>Voir les valeurs brutes</summary><dl>{Object.entries(i.raw).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'— manquant —'}</dd></div>)}</dl></details></div><span className="pf-badge warning">Exclue</span></article>)}</section><section className="pf-card"><h3>Règles de préparation</h3><ol className="pf-recipe"><li>Lire les colonnes nommées du CSV UTF-8 et préserver les numéros de lignes.</li><li>Normaliser les espaces et les séparateurs décimaux, sans changer les valeurs.</li><li>Contrôler les identifiants, les montants, les échéances et les cibles.</li><li>Isoler les lignes ambiguës et recalculer uniquement sur les lignes retenues.</li></ol><p className="pf-muted">La préparation de ce prototype est adaptée au modèle fourni. Les classeurs Excel libres, la classification assistée et la validation multi-utilisateur nécessitent une intégration supplémentaire.</p></section></>}
 <section className="pf-ask"><div><Search size={22}/><div><h3>Interrogez cette revue.</h3><p>Réponses calculées sur la sélection active · commandes guidées</p></div></div><form onSubmit={e=>{e.preventDefault();if(query.trim())ask(query);}}><label className="pf-sr" htmlFor="pf-question">Votre question</label><input id="pf-question" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Quels programmes sont en retard ?" maxLength={500}/><button className="pf-primary" disabled={!query.trim()} aria-label="Poser la question"><ArrowRight size={20}/></button></form><div className="pf-suggestions">{['Dépenses par province','Programmes en retard','Coûts restants +10 %'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={13}/></button>)}</div>{answer&&<p className="pf-answer" role="status">{answer}</p>}</section><footer className="pf-footer"><span>LUMNIA · LIGHT WHERE THERE’S NONE.</span><span>Démo autonome · aucune connexion aux systèmes de l’État</span></footer></main></div>
 {detail&&<dialog ref={dialogRef} className="pf-dialog" onCancel={()=>setDetail(null)} onClick={e=>{if(e.target===e.currentTarget)setDetail(null);}}><div className="pf-between"><h2>Fiche source · {detail.id}</h2><button aria-label="Fermer la fiche" onClick={()=>setDetail(null)}>×</button></div><p>{filename} · ligne {detail.sourceRow}</p><dl>{Object.entries(detail).filter(([k])=>k!=='sourceRow').map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl><p>Source de démonstration. Les indicateurs découlent de ces valeurs, sans certification externe.</p></dialog>}
 </div>;
}
